#!/bin/sh

#USER_DRAW_COUNT=$1
CURRENT_DIR=`pwd`
mkdir $CURRENT_DIR/lottoDir

function testFunc() {
	echo hello
}

function lottoDraw() 
{
	echo "`shuf -i 1-50 -n 5`"
}

function bonusDraw()
{
	echo "`shuf -i 1-10 -n 1`"
}

function testFunction() {
	echo "Hello"
}

function drawFiles() {
for draw in $(eval echo "{1..$1}")
do
	#echo $draw
	#echo "This is draw includes normal balls $(lottoDraw) and bonus ball $(bonusDraw)."
	echo -e "$(lottoDraw)\n$(bonusDraw)" > $CURRENT_DIR/lottoDir/userDraw$draw.`date +%m%d%Y`
done
}

function splitGuess() {
GUESS_STR=$USER_GUESSES
DRAW_COUNT=$DRAW_COUNT

for guess in $(eval echo "{1..$DRAW_COUNT}")
do 
	#echo "This is guess number: $guess"
	#echo $GUESS_STR
	PARSED_GUESS=`echo $GUESS_STR | cut -d';' -f$guess` 
	echo $PARSED_GUESS | tr ' ' '\n' > $CURRENT_DIR/lottoDir/userGuess$guess.`date +%m%d%Y`

done
}


function compareGuess() {
	LOTTO_DIR=$CURRENT_DIR/lottoDir
	SKIP_COUNT=$DRAW_COUNT

	declare -a MATCH_ARR
	for i in $(eval echo "{1..$DRAW_COUNT}")
	do
		#echo "This is iteration $i."
		STD_GUESS_i=$(cat $LOTTO_DIR/userGuess$i*| head -5 | sort -h)
		POWER_GUESS_i=$(cat $LOTTO_DIR/userGuess$i*| tail -1)
		#echo $STD_GUESS_i
		#echo $POWER_GUESS_i

		STD_DRAW_i=$(cat $LOTTO_DIR/userDraw$i*| head -5 | sort -h)
		POWER_DRAW_i=$(cat $LOTTO_DIR/userDraw$i*| tail -1)
		#echo $STD_DRAW_i
		#echo $POWER_DRAW_i
		
		#echo $STD_GUESS_i
		#echo $STD_DRAW_i

		#echo $POWER_GUESS_i
		#echo $POWER_DRAW_i

		for j in $(eval echo "{1..$(( $DRAW_COUNT*2-1 ))}")
		do
			STD_GUESS_pos=$(echo $STD_GUESS_i | awk -v j=$j '{print $j}')
			STD_DRAW_pos=$(echo $STD_DRAW_i | awk -v j=$j '{print $j}')

			#echo $STD_GUESS_pos
			#echo $STD_DRAW_pos

			if (( "$STD_GUESS_pos"=="$STD_DRAW_pos" ))
			then 
				#echo "There's a match!"
				#echo $STD_GUESS_pos
				MATCH_ARR+=($STD_GUESS_pos)
			#else
				#echo "Whammy!"
			fi
		done

	if (( $(echo ${MATCH_ARR[@]} | wc -w)=="$DRAW_COUNT" ))
        then
                echo "You won this lottery draw!!"
	elif (( $(echo ${MATCH_ARR[@]} | wc -w)>0 ))
	then
                #echo ${MATCH_ARR[@]}
                echo -e "You did not win this lottery draw, but you have $(echo ${MATCH_ARR[@]} | wc -w) matches!! Namely, ${MATCH_ARR[@]}\n"
	else
		echo -e "Apologies, boo, for lottery draw #$i, you have NO matches! :'(\n"
	fi

	done	

	#echo ${MATCH_ARR[@]}

	#if (( $(echo ${MATCH_ARR[@]} | wc -w)=="$DRAW_COUNT" ))
	#then
	#	echo "You won this lottery draw!!"
	#else
	#	echo ${MATCH_ARR[@]}
	#	echo "You have $(echo ${MATCH_ARR[@]} | wc -w) matches!!"
	#fi 

}
