#!/bin/sh

#USER_DRAW_COUNT=$1
CURRENT_DIR=`pwd`
mkdir $CURRENT_DIR/lottoDir

function lottoDraw() 
{
	echo "`shuf -i 1-50 -n 5`"
}

function bonusDraw()
{
	echo "`shuf -i 1-10 -n 1`"
}

function drawFiles() {
	echo -e "$(lottoDraw)\n$(bonusDraw)" > $CURRENT_DIR/lottoDir/userDraw.`date +%m%d%Y`
}

function splitGuess() {
GUESS_STR=$USER_GUESSES
DRAW_COUNT=$DRAW_COUNT

for guess in $(eval echo "{1..$DRAW_COUNT}")
do 
	#echo "This is guess number: $guess"
	#echo $GUESS_STR
	PARSED_GUESS=`echo $GUESS_STR | cut -d';' -f$guess` 
	echo $PARSED_GUESS | tr ' ' '\n' > $CURRENT_DIR/lottoDir/userGuess$guess.`date +%m%d%Y`

done
}


function compareGuess() {
	LOTTO_DIR=$CURRENT_DIR/lottoDir
	DRAW_COUNT=$DRAW_COUNT

	#echo "$(cat $LOTTO_DIR/userDraw*)" 

	STD_DRAW_i=$(cat $LOTTO_DIR/userDraw*| head -5 | sort -h)
	POWER_DRAW_i=$(cat $LOTTO_DIR/userDraw*| tail -1)

	#echo $STD_DRAW_i
	#echo -e $POWER_DRAW_i"\n"

	for i in $(eval echo "{1..$DRAW_COUNT}")
	do		
		#echo -e "- - - -  - - - - - - - - - - - - - - - - This is iteration $i"
		declare -a MATCH_ARR=()
		declare -a POWER_ARR=()
		
		STD_GUESS_i=$(cat $LOTTO_DIR/userGuess$i*| head -5 | sort -h)
		POWER_GUESS_i=$(cat $LOTTO_DIR/userGuess$i*| tail -1)

		for j in {1..5}
		do
			

			STD_GUESS_pos=$(echo $STD_GUESS_i | awk -v j=$j '{print $j}')
			
			STD_DRAW_pos=$(echo $STD_DRAW_i | awk -v j=$j '{print $j}')

			#echo $STD_GUESS_pos
			#echo $STD_DRAW_pos

			if (( $(echo $(echo $STD_DRAW_i | grep -w -- "$STD_GUESS_pos") | wc -w)>0 ))
			then
				#echo "There's a match!"
				MATCH_ARR+=($STD_GUESS_pos)
			fi
		done

		if (( "$POWER_GUESS_i" == "$POWER_DRAW_i" ))
		then
			#echo "Power ball matches!"
			POWER_ARR+=($POWER_GUESS_i)
		fi
		
		if (( $(echo ${MATCH_ARR[@]} | wc -w)==5 && $(echo ${POWER_ARR[@]} | wc -w)==1 ))
		then
			echo -e "You won this lottery draw!!\n"
		elif (( $(echo ${MATCH_ARR[@]} | wc -w)>0 || $(echo ${POWER_ARR[@]} | wc -w)>0 ))
		then
			echo "Sorry, you did not match all the winning lottery numbers for draw $i, but you did match some!"

			if (( $(echo ${POWER_ARR[@]} | wc -w)>0 ))
			then
				echo -e "The matching lottery numbers are: ${MATCH_ARR[@]} with powerball match: ${POWER_ARR[@]}!\n"
			else
				echo -e "The matching lottery numbers are: ${MATCH_ARR[@]}!\n"
			fi
		else
			echo -e "Sorry, there no matches for lottery draw $i!\n"
		fi
	done
}
